[package]
name = "openfoodfacts"
version = "0.1.0"
authors = ["jjdo"]
edition = "2018"

[features]
# rewqest: By defaut in blocking mode.
blocking = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.10.4"
