[package]
name = "openfoodfacts"
version = "0.1.0"
authors = ["jjdo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version = "0.10.4", features = ["blocking", "json"]}
url = "2.1.1"
